# Generated by Django 2.0.5 on 2020-12-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('Realisateur', models.CharField(max_length=42)),
                ('Contenu', models.TextField(null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date de Parution')),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudApp.Categorie')),
            ],
        ),
    ]
