# Generated by Django 2.0.5 on 2020-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Categorie',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
