# Generated by Django 2.0.5 on 2020-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0003_auto_20201224_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Date',
            field=models.DateField(verbose_name='dd-mm-yyyy'),
        ),
    ]
