# Generated by Django 2.0.5 on 2020-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0004_auto_20201226_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Date',
            field=models.DateField(),
        ),
    ]
