# Generated by Django 3.1.2 on 2021-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0005_auto_20201226_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Note_HG', models.IntegerField()),
                ('Note_ANG', models.IntegerField()),
                ('Note_FR', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
