# Generated by Django 3.1.2 on 2021-11-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0006_auto_20211031_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='Note_ANG',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='Note_FR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='Note_HG',
            field=models.FloatField(),
        ),
    ]
