# Generated by Django 4.1.4 on 2023-01-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0011_candidat_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='Note_ANG',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='Note_FR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='Note_HG',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
